### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by michaelpumo** [alexjoverm/v-lazy-image#100]
In Vue 2 (Nuxt.js), importing like so results in the above error:

`import VLazyImage from 'v-lazy-image/v2/v-lazy-image.es.js'`

Importing via (as recommended in the docs):

`import VLazyImage from 'v-lazy-image/v2'`

...results in:

Cannot find module 'v-lazy-image/v2'

Version `2.0.1` therefore appears completely broken in Vue 2. Any ideas?

**Comment by romain-lgr** [comment]
I had a similar error but I could use the package with Nuxt bridge by doing the following:

`import VLazyImage from "v-lazy-image/v2"` in my compoment

Add to `nuxt.config.js`:
```
build: {
    transpile: [
      'v-lazy-image/v2'
    ]
}
```

Then `nuxi dev` and `nuxi generate` work fine

**Comment by alexjoverm** [comment]
Should be fixed in latest v2.1.0. Please reopen if it's not the case
