### ISSUE TITLE
Does this have any advantages over https://github.com/RadKod/v-lazy-component ?

### ISSUE THREAD

**Issue by mikob** [alexjoverm/v-lazy-image#105]
It seems https://github.com/RadKod/v-lazy-component supersedes the functionality here, and allows for more flexibility. E.g. specifying `type` attributes in source.

**Comment by mikob** [comment]
Also I think a lot of ppl are using this plugin unnecessarily when `<img src="image.jpg" alt="..." loading="lazy">` will suffice. I think it should be mentioned in the docs.

**Comment by alexjoverm** [comment]
The purposes are different. `loading="lazy"` could be implemented by this lib under the hood, but it's not the only functionality it offers. Feel free to create an issue or PR with proposals
