### ISSUE TITLE
error Can't find variable: IntersectionObserver

### ISSUE THREAD

**Issue by sldobri** [alexjoverm/v-lazy-image#12]
[Vue warn]: Error in mounted hook: "ReferenceError: Can't find variable: IntersectionObserver"

found in

---> <VLazyImage>

**Comment by alexjoverm** [comment]
Hi @sldobri, it seems like the browser you're using it doesn't support IntersectionObserver. As [stated in the doc](https://github.com/alexjoverm/v-lazy-image#usage) you must load the polyfill :).
