### ISSUE TITLE
Intersection Options should have a factory function as default

### ISSUE THREAD

**Issue by bovas85** [alexjoverm/v-lazy-image#13]
`Invalid default value for prop "intersectionOptions": Props with type Object/Array must use a factory function to return the default value
`
Getting an error like this with Nuxt. 

Will try to PR something in a bit

**Comment by ay13** [comment]
@bovas85 is this your PR for this issue?

https://github.com/alexjoverm/v-lazy-image/pull/14

**Comment by bovas85** [comment]
Yes indeed

**Comment by alexjoverm** [comment]
Thanks @bovas85 for the issue and the PR! I've left a comment in #14 :)

**Comment by alexjoverm** [comment]
Closed by #14
