### ISSUE TITLE
Feature: Medium-style blur effect

### ISSUE THREAD

**Issue by andreynazarov3** [alexjoverm/v-lazy-image#21]
There's article https://alligator.io/vuejs/progressive-image-rendering/
A guy uses this library and makes blur effect with svg filter.
I tried to use it in my project but it seems to not be working on iOS devices at all, also problems with Firefox and Edge.
So I guees this should be implemented in this library the way like medium does this - with ```<canvas>``` element. There's already blur library https://github.com/flozz/StackBlur, just need to implement transition effect.

**Comment by alexjoverm** [comment]
Hey @andreynazarov3! It could be nice to have this feature, although I wouldn't have it opt-in in this library.

What about allowing the user to use scoped slots, so we make the rendering flexible? That's something it could work as well for #17, since the user literally could render it in any way it wants, while still encapsulating the lazy-loading logic

**Comment by alexjoverm** [comment]
@andreynazarov3 what could be needed for doing the transition with `<canvas>`? I think I'll update the article https://alligator.io/vuejs/progressive-image-rendering as well, when I wrote the article I didn't think about the canvas thing

**Comment by andreynazarov3** [comment]
@alexjoverm I've made such transition with just using css transition for opacity. 1) Load small image with 0 opacity 2) Generate blurred canvas and show it 3) Load large image with 0 opacity 4) Change large image opacity to 1. So this ends up with hamburger of Small Image/Canvas/Large Image in one block.

There is one bug in this logic coming from canvas when using srcset with media queries.
In case if you asre using images with different aspect ratios If you resize screen after loaded image canvas will show up in wrong aspect ratio.

**Comment by andreynazarov3** [comment]
@alexjoverm BTW, svg filter in fact should work in iOS, it's just intersection observer not supported, so needs polifyll. But, anyway, as for me, I think canvas blur just looks better, and maybe in fact less CPU consuming.

**Comment by althe3rd** [comment]
I'm encountering the same issue when trying to do progressive loading, ios browsers don't work.  Is this just a known issue with the way the effect is accomplished and I should use a different js module to accomplish this effect? Or is there something I can do with v-lazy-load that will resolve this there?

Can't really afford to just not show images clearly in ios.

**Comment by althe3rd** [comment]
@andreynazarov3 Is the polyfill something that should be included in the default v-lazy-image package or something I can add myself separately if I am applying more control over the blur up technique? I haven't seen any updates or examples that show v-lazy-image working in iOS so I may just have to try another or write my own from scratch.

**Comment by andreynazarov3** [comment]
yes, you should add yourself intersection observer polyfill, thats all
