### ISSUE TITLE
How handle Image load broken?

### ISSUE THREAD

**Issue by ngohuunam** [alexjoverm/v-lazy-image#25]
Hi
I tried to bind event @error but no luck. Is there any way to handle this case?

**Comment by alexjoverm** [comment]
Hi! That's not implemented right now. Would you open a PR? It shouldn't be hard to implement, since it would be similar to how the [load event](https://github.com/alexjoverm/v-lazy-image/blob/master/src/index.js#L38) is done right now.

**Comment by jeancarlos** [comment]
What I did:
```
<v-lazy-image
  @error.native="imgURL"
  src="image.jpg"
  src-placeholder="placeholder.jpg"
/>
```

and then:
```
imgURL(e) {
  e.target.src = `placeholder.jpg`;
  e.target.classList.add("v-lazy-image-loaded");
},
```

Not perfect solution, but it did the job incredibly well.

**Comment by GadQ** [comment]
Actually @error.native doesn't work for me.
If there is intersect/load event emitted it would be nice to also have error emitted.

**Comment by alexjoverm** [comment]
This should be implemented in latest version
