### ISSUE TITLE
Start loading image before it comes into view?

### ISSUE THREAD

**Issue by docmattman** [alexjoverm/v-lazy-image#26]
Is it possible to have images start loading before they come into view?  Right now, it seems like it begins to load the image as soon as it is scrolled into the view.  Is it possible to start loading the image 100px or 200px (any custom value) ahead of time?  this would help minimize the amount of time the placeholder is seen while the real image is downloaded.  Is there some sort of padding setting to allow this?

**Comment by alexjoverm** [comment]
You can do that by setting the `rootMargin` option of the `intersection-options` prop https://github.com/alexjoverm/v-lazy-image/blob/master/README.md#props

**Comment by alexjoverm** [comment]
So, this would load it 500px before reaching the viewport:

```html
<v-lazy-image :intersection-options="{ rootMargin: '500px' }"/>
```

**Comment by muhammedjenos** [comment]
Is there a way to globally apply this instead of every v-lazy-image component?
