### ISSUE TITLE
Attribute Inheritance

### ISSUE THREAD

**Issue by rcpires** [alexjoverm/v-lazy-image#40]
Would be very useful to be able to pass dynamic attributes (or a least class property) to v-lazy-image component, for example to add a custom class to rendered img tag:

So this code:

`<v-lazy-image class="my-custom-class"` ...></v-lazy-image>

Would generates a img tag with my custom class:

`<img class="v-lazy-image v-lazy-image-loaded my-custom-class" ... />`

Thanks!

**Comment by frandiox** [comment]
+1 to this, when using `use-picture` prop, the `<picture>` element gets the class instead of the `<img>`. Not sure if that's useful in some case but there should be a way to add classes to the `<img>` element for `object-fit: cover;`, etc.

Thanks for the tool!

**Comment by alexjoverm** [comment]
Hey! For <img> should work correctly, but true that when using use-picture it gets added to the root element. That's just how Vue 2 works, but maybe can be done via a prop

**Comment by alexjoverm** [comment]
Closing in favor of #47
