### ISSUE TITLE
v-lazy-image-loaded not being added once the image is fully loaded

### ISSUE THREAD

**Issue by jagroop** [alexjoverm/v-lazy-image#41]
v-lazy-image-loaded not being added once the image is fully loaded

https://github.com/alexjoverm/v-lazy-image#progressive-loading

**Comment by mornir** [comment]
Are you using PurgeCSS and/or Tailwind? If yes, make sure that you white-listed the 'v-lazy-image-loaded' class.
```js
// nuxt.config.js
{
  purgeCSS: {
    whitelist: ['v-lazy-image-loaded'],
  },
}
```
In my case, I preferred to simply move the class from the external stylesheet into layout.vue. Styles in vue components/layouts are not "purged".
