### ISSUE TITLE
Not working iPhone 7 plus with IOS 11

### ISSUE THREAD

**Issue by jigeshraval** [alexjoverm/v-lazy-image#42]
Not working properly with iPhone browsers such as Chrome, Safari and Mozilla

**Comment by mornir** [comment]
You'll need to install the w3c Intersection Observer polyfill in case you're targeting a browser which doesn't support it.
Intersection Observer is supported from iOS v12.2

**Comment by EnzoBatista** [comment]
@mornir How did you implement this fix?

**Comment by webistomin** [comment]
> @mornir How did you implement this fix?

https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by EnzoBatista** [comment]
@mornir I've already done it, but thank you anyway

**Comment by mornir** [comment]
https://github.com/Timkor/nuxt-polyfill (there's an example for intersection-observer)

**Comment by mornir** [comment]
@EnzoBatista Then please close this issue :-)

**Comment by mornir** [comment]
@jigeshraval Can you please close the issue?

**Comment by teuzinPereira** [comment]
> > @mornir How did you implement this fix?
> 
> https://github.com/w3c/IntersectionObserver/tree/master/polyfill

@webistomin I installed polyfill as mention in docs, but the problem persist. 
According docs, just need to install via NPM and use require('intersection-observer').

I xcode console the error reported before is not showing anymore, but the image that´s suposeed to be load, is not showing.

There is any other configuration to be done?

tks

**Comment by webistomin** [comment]
> > > @mornir How did you implement this fix?
> > 
> > 
> > https://github.com/w3c/IntersectionObserver/tree/master/polyfill
> 
> @webistomin I installed polyfill as mention in docs, but the problem persist.
> According docs, just need to install via NPM and use require('intersection-observer').
> 
> I xcode console the error reported before is not showing anymore, but the image that´s suposeed to be load, is not showing.
> 
> There is any other configuration to be done?
> 
> tks

I'm usin nuxt.js, so I can only help you with that framework.

Alternatively, you can install pollyfill through Polyfill.io.

Just insert this
`<script src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CIntersectionObserverEntry"></script>`
