### ISSUE TITLE
Doesn't work if image is in no-ssr component

### ISSUE THREAD

**Issue by mrleblanc101** [alexjoverm/v-lazy-image#48]
If the image is in a <no-ssr> component, it will never load if it is in the screen when the page initialy load. If i scroll past the content and come back, it will load and trigger the Observer and replace the image.

**Comment by michaelpumo** [comment]
I get the same issue with Nuxt but actually the opposite to you. If I use it within <no-ssr> tag it works fine.

The reason I think images do not load until you go past and come back, is that the props for the src to the component holding the image are only resolved **after** v-lazy-image checked the src.

**Comment by alexjoverm** [comment]
We're using it within no-ssr in production and it works. Please provide a reproducible example if you still find this issue.
