### ISSUE TITLE
Wraping the img in a picture tag doesn't work for chrome 75

### ISSUE THREAD

**Issue by RomanNagornyi** [alexjoverm/v-lazy-image#49]
Hello

For this version, lazy loading is by default in the browser and this crashes the plugin. A tag 
```html
<picture></picture>
```

 is empty.

Hope for help.

**Comment by alexjoverm** [comment]
Hi @RomanNagornyi. Sorry but I need more info to fully understand the issue. Could you provide more info, and maybe a demo to reproduce it?

**Comment by RomanNagornyi** [comment]
Hello

I have this issue only in Chrome for last month. For others browsers everything is ok. I use Nuxt with nested components. The problem is that inside these components v-lazy-image is never intersected. IntersectionObserver for empty 
```html
<picture></picture>
```

is never fired to be "isIntersecting"

```js
if (image.isIntersecting) {
...
}
```

But if I make a picture tag not empty? like this
```js
return h("picture", { on: { load: this.load } }, this.intersected ? [ this.$slots.default, img ] : ["."] );
```
image is loaded. (I added "dot" ["."])

Maybe this is a bug for IntersectionObserver in Chrome. I don't know.

**Comment by RomanNagornyi** [comment]
I have added some dimension for picture tag and it works.
```js
    if (this.usePicture) {
      if (!this.intersected) {
        return h("picture", {attrs: {style: "padding: 1px;"}, domProps: this.$attrs});
      } else {
        return h("picture", {on: {load: this.load}}, [this.$slots.default, img]);
      }
    } else {
      return img;
    }
```

maybe it worth a pull request ? )

**Comment by simonhermann** [comment]
This seems to fix it for me, at least when not using `use-picture` 
```
/deep/ picture,
/deep/ img {
  min-height: 1px;
  min-width: 1px;
}
```

When enabling `<picture>`, chrome still does not load the images sometimes..

**Comment by alexjoverm** [comment]
Hey folks, thanks a lot for your effort on investigating about this issue! Much appreciated.

I see some solutions are proposed already in the thread. Please feel free to submit a PR and I'll review it ;)

**Comment by taka66** [comment]
Any update for this issue?

**Comment by melalj** [comment]
Is this project no longer maintained?

**Comment by alexjoverm** [comment]
Should be fixed in latest version
