### ISSUE TITLE
 Standard Error Image

### ISSUE THREAD

**Issue by wallysonn** [alexjoverm/v-lazy-image#53]
How to set a default image if the main image fails?

**Comment by JFGHT** [comment]
`            <v-lazy-image
                :src="slotProps.firstImage || require('@/assets/images/property/properties-placeholder.jpg')"
                :src-placeholder="require('@/assets/images/property/properties-placeholder.jpg')"
            />`

**Comment by alexjoverm** [comment]
You can do it by using the @error event
