### ISSUE TITLE
Basic Configuration with local images

### ISSUE THREAD

**Issue by andresclua** [alexjoverm/v-lazy-image#54]
hi there,
First of all, plugin si working amazing with cdn images, but when I try to apply it with local images, is not working at all.

<template>
  <div id="app">
    <div id="nav">
      <h1 class="jumbotron-heading">Album example</h1>
    </div>
    <router-view/>
    <img alt="Vue logo" src="./assets/logo.png">
    <hr>
    <v-lazy-image src="./assets/logo.png" />
  
  </div>
</template>

path is correct because I have 2 images with same src.

Thanks in advance

**Comment by JFGHT** [comment]
`            <v-lazy-image
                :src="slotProps.firstImage || require('@/assets/images/property/properties-placeholder.jpg')"
                :src-placeholder="require('@/assets/images/property/properties-placeholder.jpg')"
            />`

**Comment by highoncarbs** [comment]
Would it increase JS bundle size ?

**Comment by highoncarbs** [comment]
Move your images to `static` folder ,  and  ` <VLazyImage :src="/images/hello.jpg" />` , where images is the folder in static folder
