### ISSUE TITLE
crossorigin attribute

### ISSUE THREAD

**Issue by san-kumar** [alexjoverm/v-lazy-image#65]
I'm using this in a media gallery where I'm using a crossorigin="anonymous" tag so that I can use the selected image on to a canvas.

Is there any way to pass the crossorigin property to the image tag upon loading?

Thanks.

**Comment by AndrewBogdanovTSS** [comment]
Do you use img or picture tags?

**Comment by san-kumar** [comment]
img tags mostly

**Comment by alexjoverm** [comment]
You should be able to do that. Please reopen with a repro demo in case it doesn't
