### ISSUE TITLE
$event is showing undefined when function calling in @load

### ISSUE THREAD

**Issue by sijith-bridge** [alexjoverm/v-lazy-image#69]
I tried to call a function in @load 
<v-lazy-image :src="imageCDNPath+product.ShelfFile.FileName" @load="whenImgLoaded($event)"
               />

but event is showing undefined in function, is there anything to add ?

**Comment by Techassi** [comment]
Can confirm. It seems like only the error handler passes in the element (see [L41](https://github.com/jjragomes/v-lazy-image/blob/1759850aa2a8ce3f7808f714f6a12b5fa6e42f97/src/index.js#L41))

**Comment by Techassi** [comment]
I have gone ahead and wrote my own package. It improves on different functions, fixes this issue and is Vue 3 compatible. Feel free to take a look [here](https://github.com/Techassi/vue-lazy-image)

**Comment by alexjoverm** [comment]
There was major rework for v2.0.0. Feel free to open a new PR with the change in `index.js` and `index-v2.js` :)

**Comment by alexjoverm** [comment]
Fixed in latest version
