### ISSUE TITLE
Image dimensions warning message

### ISSUE THREAD

**Issue by oleksanrei** [alexjoverm/v-lazy-image#72]
I'm getting a warning message when using this library on the Nuxt client-only block

`[Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323`

**Comment by AndrewBogdanovTSS** [comment]
@oleksanrei this warning is not related to v-lazy-image lib, it's related to using `loading=lazy` attribute on the image. The real problem of v-lazy-image is that it doesn't keep image dimensions when lazy loading an image so it first appears collapsed. I guess the warning above is just highlighting this problem. Please, provide a component code that you use for managing v-lazy-image images

**Comment by alexjoverm** [comment]
You're free to set the dimensions attributes. That said, the library hasn't been tested with `loading=lazy` yet, but it's a feature I'd be happy to have. Closing this for now
