### ISSUE TITLE
inheritAttrs: false

### ISSUE THREAD

**Issue by webistomin** [alexjoverm/v-lazy-image#74]
Hi! I ran into the problem that `v-lazy-image` does not inherit attributes. For what reasons does the library specify [`inheritAttrs: false`](https://github.com/alexjoverm/v-lazy-image/blob/master/src/index.js#L23)? Is there a way to pass attributes?

**Comment by alexjoverm** [comment]
Actually you should be able to pass them. `inheritAttrs:false` is there because the libs manually adds the attrs to the right element, having grained control over it https://github.com/alexjoverm/v-lazy-image/blob/master/v-lazy-image/index-v2.js#L50. Feel free to reopen if it's not the case
