### ISSUE TITLE
Missing `alt` attibute

### ISSUE THREAD

**Issue by Xaviju** [alexjoverm/v-lazy-image#8]
MDN: This attribute defines the alternative text describing the image. Users will see this text displayed if the image URL is wrong, the image is not in one of the supported formats, or if the image is not yet downloaded.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt

Cannot PR it right now but basically add it to props:

```
props: {
    alt: {
      type: String,
      default: ""
    }
  }
```
and to render:
```
render(h) {
    return h("img", {
      attrs: { 
       src: this.srcImage,
       alt: this.alt
      },
      class: {
        "v-lazy-image": true,
        "v-lazy-image-loaded": this.loaded
      }
    });
  }
```
Sorry not sure if render works as in my example since I've never used the render function before :)

**Comment by Xaviju** [comment]
Oh, I've seen in [this example](https://codesandbox.io/s/r5wmj970wm) that it accepts the alt attribute already... closing this

**Comment by alexjoverm** [comment]
Yeah, by default all non-props attributes passed to a component in Vue.js are added to the component's root element :). Thanks for the heads up anyway!
