### ISSUE TITLE
Vue 2 - v-lazy-image 2.0.1 - Missing file extension for "v-lazy-image/v2"

### ISSUE THREAD

**Issue by darkissdark** [alexjoverm/v-lazy-image#93]
how to fix this?

**Comment by misaon** [comment]
`import VLazyImage from 'v-lazy-image/v2/v-lazy-image.es.js`

**Comment by darkissdark** [comment]
[Vue warn]: Failed to resolve async component: function CatalogSearchBar() {
    return __webpack_require__.e/* import() */(36).then(__webpack_require__.bind(null, 1775));
}
Reason: SyntaxError: Unexpected token 'export'
error: Error: render function or template not defined in component

**Comment by WoetDev** [comment]
I'm also receiving the error

`Cannot find module 'v-lazy-image/v2'` when using `import VLazyImage from 'v-lazy-image/v2'`

OR

`SyntaxError
Unexpected token 'export'` when using `import VLazyImage from 'v-lazy-image/v2/v-lazy-image.es.js'`

Any way to fix this?

**Comment by michaelpumo** [comment]
I'm getting this error too. Need an urgent fix or might have to resort to downgrading / moving to another library.

**Comment by gaethug** [comment]
@WoetDev 
I have same issue...

**Comment by GregoireF** [comment]
Hi everyone,

Same incident on a VuePress configuration with Vue2

**Comment by TheNoim** [comment]
> I'm also receiving the error
> 
> `Cannot find module 'v-lazy-image/v2'` when using `import VLazyImage from 'v-lazy-image/v2'`
> 
> OR
> 
> `SyntaxError Unexpected token 'export'` when using `import VLazyImage from 'v-lazy-image/v2/v-lazy-image.es.js'`
> 
> Any way to fix this?

I think there a two options for you:

1. Use `v-lazy-image/v2/v-lazy-image.umd.js` instead of `v-lazy-image/v2/v-lazy-image.es.js`
2. Transpile the module. You need to look up yourself how this works with the tooling which you are using. In nuxt you can add `v-lazy-image/v2/v-lazy-image.es.js` to `build.transpile` in your nuxt config.

**Comment by wjonkerhulst** [comment]
Same problem. Would be helpful to add some additional information to the documentation.

`v-lazy-image/v2/v-lazy-image.umd.js` seem to have solved the import problem for me.

**Comment by alexjoverm** [comment]
Should be fixed in latest v2.1.0. Please reopen if it's not the case
