### ISSUE TITLE
render function or template not defined in component: v-lazy-image

### ISSUE THREAD

**Issue by bhayawalaarpit** [alexjoverm/v-lazy-image#95]
**Import v-lazy-image:**
import VLazyImage from "v-lazy-image";

**Register Component**
components: {
    VLazyImage
  }

**Call the Component:**
<v-lazy-image src="/images/demo.png" alt="Stockmusic.net home page" />

Would please help me to fix this issue?

**Comment by michaelpumo** [comment]
For Vue 2, I think you need:

`import VLazyImage from "v-lazy-image/v2";`

However, this doesn't work for me and shows me: **Cannot find module 'v-lazy-image/v2'**

**Comment by GregoireF** [comment]
Hi,

Indeed the configuration of @michaelpumo is correct. However I am on the same incident to date. 
Any resolution in progress on this issue?

**Comment by alexjoverm** [comment]
Should be fixed in latest v2.1.0. Please reopen if it's not the case
